version: '2'

volumes:
  postgres_data: {}
  public_data: {}

services:

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/app/data
    env_file: .env

  redis:
    build: ./compose/redis

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /usr/local/bin/supervisord -c /supervisord.conf --nodaemon
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - public_data:/app/public
      - ./data:/app/data

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
      args:
        - configuration_file
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - public_data:/app/public
